---
title: "Good Eatin's"
description: |
  The hidden gems I didn't want to share
author:
  - name: Jacob Ford
    url: https://jford-dchcmpo.github.io/Blog/posts/2021-12-30-Redistricting-and-Racial-Targetting/
date: 2022-05-03
output:
  distill::distill_article:
    self_contained: false
---

These are the places I most love after ~4 years of North Carolina living. Most are based in Durham, no shame there, some call it the Mecca of the South. 

Click on a location, get my 'don't miss' item(s) from each. 


```{r setup, include=FALSE}
library(dplyr)
library(leaflet)
library(sf) 

library(readxl)
eats_data <- read_excel("/Users/jacobford/Documents/GitHub/Blog/Eat_Data.xlsx")


```




```{r echo=FALSE, message=FALSE, warning=FALSE}
library(RColorBrewer)
pal <- colorFactor(
  palette = 'Dark2',
  domain = eats_data$Genre
)


eats_map <- leaflet(data=eats_data) %>%
 # addTiles() %>%
 addProviderTiles("CartoDB.Positron") %>%
  addCircles(lat = eats_data$Latitutde, lng=eats_data$Longitude,
             popup=paste("Name: ", eats_data$Name, "<br>",
                          "Genre: ", eats_data$Genre, "<br>",
                          "Don't you dare miss: ", eats_data$`Don't Miss:`),
             color = ~pal(Genre),
             weight=10,
             fillOpacity = 2) %>%
  addLegend("bottomleft",
            pal=pal,
            values=~Genre)
  
  
eats_map
```

